cli: remove operations in tdp browse deployments
TOSIT-IO/tdp-lib pull request #197
Opened 2022-07-26 15:57 UTC by kpgtek

Fix #196 

The column about ```operations``` in ```deployments``` returned by ```tdp browse``` could be removed, because it can not contain a full list of operations, and this could be display with ```tdp browse <deployment_id>```.

By this way, we could thus reduce number of queries launched by ```tdp browse```.

2022-07-26 17:27 UTC, gboutry requested changes

2022-07-26 17:27 UTC, gboutry commented on tdp/cli/commands/browse.py
> -                return ",".join(operation_log.operation for operation_log in value)
If we keep the code as it was in `process_single_deployment_query`, we should keep this.

2022-07-26 17:27 UTC, gboutry commented on tdp/cli/commands/browse.py
> +    ]
Why ? The operations logs for the deployments will be queried anyway. (at l122)
You should keep it as it was.

```suggestion
    deployment_headers = [key for key, _ in keyvalgen(DeploymentLog)]
```

2022-07-27 10:55 UTC, gboutry approved these changes

2022-07-27 10:56 UTC, rpignolet approved these changes

2022-07-27 12:37 UTC, merged