refactor: use orm in queries
TOSIT-IO/tdp-lib pull request #328
Opened 2023-06-29 06:41 UTC by PaulFarault

#### Which issue(s) this PR fixes

Fixes None

#### Additional comments

- Refactor queries to all use the ORM, to make them easier to read/write.
- Add doc on queries.
- Gather all queries to a single `query` file.

TODO: document the other functions of `browse` (I'll open an issue or another PR).

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-06-29 15:08 UTC, rpignolet approved these changes

2023-06-29 15:27 UTC, sergkudinov requested changes

2023-06-29 15:27 UTC, sergkudinov commented on tdp/cli/commands/browse.py
>  from sqlalchemy.orm import joinedload
remove unused improts like `select`, `joinedload`

2023-06-30 06:40 UTC, PaulFarault commented on tdp/cli/commands/browse.py
>  from sqlalchemy.orm import joinedload
Done

2023-06-30 12:03 UTC, kpgtek approved these changes

2023-06-30 12:55 UTC, merged