Fix broken tests
TOSIT-IO/tdp-lib pull request #339
Opened 2023-06-29 14:39 UTC by sergkudinov

#### Which issue(s) this PR fixes

Fixes #333

#### Agreements

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [ ] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-06-29 14:42 UTC, sergkudinov commented
in `tdp/core/deployment/test_deployment_runner.py`, 3 tests are not currently passing because of #337:
- `test_failed_operation_stops`
- `test_deployment_is_resumed`
- `test_deployment_reconfigure_is_resumed`

2023-06-30 07:00 UTC, PaulFarault requested changes
LGTM!

Make sure to remove the `Fixes` from your comment so it won't close the issue (we still have to fix the code and the remaining tests).

2023-06-30 07:04 UTC, PaulFarault commented
@sergkudinov Do you prefer to merge this one "now" and do a second pr later to fix the remaining tests or do you want to wait for the #337 to be fixed?

2023-06-30 13:25 UTC, sergkudinov commented on tdp/core/deployment/deployment_plan.py
> +        deployment_log: Deployment information
ok

2023-07-04 11:57 UTC, sergkudinov commented
I checked this changes on #344 PR's branch, it works. Just waiting #334 merged to master...

2023-07-04 12:57 UTC, PaulFarault commented
#344 just got merged, you can go ahead.

2023-07-04 12:57 UTC, PaulFarault approved these changes
#344 just got merged, you can go ahead.

2023-07-04 13:07 UTC, sergkudinov commented
@PaulFarault
it works on my computer
43 of 43 passed

2023-07-04 13:08 UTC, sergkudinov commented
just rebased on latest master

2023-07-04 13:23 UTC, PaulFarault approved these changes
Ok it works now.

2023-07-04 13:25 UTC, merged