Add types on tests
TOSIT-IO/tdp-lib pull request #393
Opened 2023-08-10 09:06 UTC by PaulFarault

#### Which issue(s) this PR fixes

Fixes None

#### Additional comments

- Add types on tests parameters to help identify errors in test implementation.
- Display command output when cli test fails

#### Agreements

- [X] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [X] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-08-10 16:03 UTC, rpignolet requested changes
`tdp/core/models/test_deployment_log.py` line 329 (`def test_one_stale`), parameter `minimal_collections` is a `Collections` instance.

2023-08-10 17:00 UTC, PaulFarault commented
> `tdp/core/models/test_deployment_log.py` line 329 (`def test_one_stale`), parameter `minimal_collections` is a `Collections` instance.

Didn't see it as it was done in a previous commit. Thx, I fixed it.

2023-08-10 17:18 UTC, rpignolet approved these changes

2023-08-11 16:31 UTC, mdrutel commented
When I execute ```tdp service-versions```, I have the following error :
```
2023-08-11 18:30:50,262 - DEBUG - tdp.<module> - Logger initialized
Traceback (most recent call last):
  File "/home/mdrutel01/projets/git/tdp-ops/venv/bin/tdp", line 6, in <module>
    sys.exit(tdp())
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mdrutel01/projets/git/tdp-ops/tdp/tdp-lib/tdp/cli/commands/service_versions.py", line 30, in service_versions
    + tabulate(
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/tabulate.py", line 1528, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/tabulate.py", line 1191, in _normalize_tabular_data
    rows = list(map(list, rows))
TypeError: 'ComponentVersionLog' object is not iterable
```

2023-08-11 16:47 UTC, mdrutel approved these changes

2023-08-16 08:10 UTC, merged