refactor: replace OrderedDict with dict
TOSIT-IO/tdp-lib pull request #420
Opened 2023-08-31 13:05 UTC by sergkudinov

#### Which issue(s) this PR fixes

Fixes #369

#### Additional comments

> Explicit the correct types for classes that inherit from the `Mapping` abc (as `Collections`)

this seams already fixed

> Use `list` instead of `List`

also fixed

I am not sure if there is smth else to refactor. Checked with [whats new in python 3.9](https://docs.python.org/3/whatsnew/3.9.html).

#### Agreements

- [x] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-09-04 09:05 UTC, rpignolet commented
I don't know why you want to use `dict` instead of `OrderedDict`.

2023-09-04 09:24 UTC, sergkudinov commented
In the issue you mention: 

> Remove `OrderedDict`

I understood we replace `OrderedDict`, which `dict` does the same since Python 3.6, it also keeps items ordered ([reference](https://realpython.com/python-ordereddict/#choosing-between-ordereddict-and-dict)) and a bit more efficiente than `OrderedDict`.

To my mind, it worth to do that.

2023-09-05 09:06 UTC, sergkudinov commented
@PaulFarault @rpignolet 
what do you think?

2023-09-05 09:15 UTC, rpignolet commented
I think is better to keep `OrderedDict` to no rely on detail implementation. Moreover, with `OrderedDict` it's explicit that we want an order for keys.

2023-09-05 11:23 UTC, PaulFarault commented
Thx. As we're looking at it, could you add a commit to fix the Iterator please (make it a Generator).

2023-09-05 14:42 UTC, rpignolet approved these changes

2023-09-06 07:27 UTC, PaulFarault requested changes
I saw that you linked this PR to #369 which will close it. However, it seems that there are still some types to migrate. Could you please either fix the whole issue or transform the `Fixes` keyword to `Part of`?

2023-09-06 07:27 UTC, PaulFarault commented on tdp/core/variables/service_variables.py
> +    ) -> Generator[OrderedDict[str, Variables]]:
Generator generic takes 3 type parameters: `Generator[YieldType, SendType, ReturnType]`.

```suggestion
    ) -> Generator[OrderedDict[str, Variables], None, None]:
```

2023-09-07 10:34 UTC, sergkudinov commented on tdp/core/variables/service_variables.py
> +    ) -> Generator[OrderedDict[str, Variables]]:
done

2023-09-07 11:19 UTC, PaulFarault approved these changes

2023-09-07 13:53 UTC, merged