issue 346 transformed playbook.py into script instead of TDP cli
TOSIT-IO/tdp-lib pull request #481
Opened 2023-10-26 08:35 UTC by SteBaum

#### Which issue(s) this PR fixes

issue #346

#### Additional comments

- Removed the playbook command in __main_.py.
- Transformed playbook.py into a script a developer can use without the cli command by removing the click instructions and by introducing a parser for the terminal.
- Light modification to the function, for instance the code does not break if the output directory already exists; if a new collection is passed in the command it will add it to the already existing directory, otherwise no changes will occur. 

#### Agreements

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [ ] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-10-31 08:44 UTC, PaulFarault requested changes

2023-10-31 08:44 UTC, PaulFarault commented on scripts/playbooks.py
> +            for col in args.collection or TDP_COLLECTION_PATH.split(":")
You should use `os.pathsep` as a separator.

2023-10-31 08:44 UTC, PaulFarault commented on scripts/playbooks.py
> +    collections: Collections,
Add a condition before calling playbooks if you don't want `collections` to be empty.

2023-10-31 08:44 UTC, PaulFarault commented on scripts/playbooks.py
Would be nice to add a docstring describing the purpose of this script

2023-11-22 09:40 UTC, PaulFarault commented
We could leverage click's features to parse options (and use the ones defined for the cli). This doesn't mean that the command will is part of the CLI.

2023-11-22 09:40 UTC, PaulFarault submitted a review, later dismissed
We could leverage click's features to parse options (and use the ones defined for the cli). This doesn't mean that the command will is part of the CLI.

2023-12-05 14:32 UTC, PaulFarault requested changes

2023-12-08 09:03 UTC, SteBaum commented
I have changed the PR. It now does what is described in the description above and does not change failure if the meta outputdirectory already exists.

2024-01-11 16:47 UTC, rpignolet approved these changes

2024-01-12 08:04 UTC, merged