feat: catch exceptions
TOSIT-IO/tdp-lib pull request #482
Opened 2023-10-26 13:49 UTC by sergkudinov

#### Which issue(s) this PR fixes

Fixes #449

#### Additional comments

#### Agreements

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [ ] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-10-30 08:40 UTC, PaulFarault requested changes
Thanks, this version is much better than the previous PR!

2023-10-30 08:40 UTC, PaulFarault commented on tdp/cli/utils.py
> +            print("Error:", e)
Use click instead of the standard lib:

```suggestion
            click.echo(f"Error: {e}", err=True)
```

2023-10-30 14:58 UTC, sergkudinov commented on tdp/cli/utils.py
> +            print("Error:", e)
done

2023-10-30 14:59 UTC, PaulFarault approved these changes

2023-10-31 13:27 UTC, rpignolet approved these changes

2023-10-31 14:35 UTC, merged